name: Builder Win

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build-win:
    name: Build PluginLoader for Win
    runs-on: windows-2022

    steps:
    - name: Checkout 🧰
      uses: actions/checkout@v3

    - name: Set up NodeJS 18 💎
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Set up Python 3.11.4 🐍
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        
    - name: Install Python dependencies ⬇️
      working-directory: ./backend
      run: C:\Users\runneradmin\.local\bin\poetry install --no-interaction

    - name: Install JS dependencies ⬇️
      working-directory: ./frontend
      run: |
        npm i -g pnpm
        pnpm i --frozen-lockfile

    - name: Build JS Frontend 🛠️
      working-directory: ./frontend
      run: pnpm run build

    - name: Build Python Backend 🛠️
      working-directory: ./backend
      run: C:\Users\runneradmin\.local\bin\poetry run pyinstaller pyinstaller.spec

    - name: Build Python Backend (noconsole) 🛠️
      working-directory: ./backend
      run: $env:DECKY_NOCONSOLE = 1; C:\Users\runneradmin\.local\bin\poetry run pyinstaller pyinstaller.spec

    - name: Upload package artifact ⬆️
      uses: actions/upload-artifact@v3
      with:
        name: PluginLoader Win
        path: |
          ./backend/dist/PluginLoader.exe
          ./backend/dist/PluginLoader_noconsole.exe
    
