name: Type Check

on:
  push:
  pull_request:

jobs:
  typecheck:
    name: Run type checkers
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3 # Check out the repository first.

      - name: Set up Python 3.10.6 🐍
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install Python dependencies ⬇️
        working-directory: backend
        run: poetry install --no-interaction

      - name: Install TypeScript dependencies
        working-directory: frontend
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile

      - name: Run pyright (Python)
        uses: jakebailey/pyright-action@v1
        with:
          python-version: "3.10.6"
          no-comments: true
          working-directory: backend

      - name: Run tsc (TypeScript)
        working-directory: frontend
        run: $(pnpm bin)/tsc --noEmit